/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import gym_app.entrevista_rutina;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent; 
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
<<<<<<< HEAD
 * @author ANDREA MORALES CHAVEZ                  
=======
 * @author ANDREA MORALES CHAVEZ uuyuy jjjggh
>>>>>>> origin/Andrea
 */
public class compraprod extends javax.swing.JFrame {

    /**
     * Creates new form Rutinas
     */
     private JPanelConFondo fondo;
    private Point mPoint;
    public compraprod() {
         setUndecorated(true);
        initComponents();
        
        setLocationRelativeTo(this);
        
        fondo = new JPanelConFondo("src/Image/perfilF.png");
        Fondo.setLayout(new BorderLayout());
        Fondo.add(fondo);
        // foto de salir
        SetImageButton("src/Image/X.png", Salir);
        SetImageButton("src/Image/regresar.png", Regresarbtn);
       
        

        /*IMAGENES*/
       /*
        Document doc = imctxt.getDocument();
        doc.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Insert");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Eliminar");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Cambio");
            }

            public void actualizarImagen() {
                try {
                    // Obtener el valor como un número

                    double imc = Double.parseDouble(imctxt.getText());

                    // Determinar qué imagen mostrar según el valor ingresado
                    ImageIcon imagen;
                    if (imc < 18.5) {
                        imagen = new ImageIcon("src/Image/1azul.png");
                        System.out.println("Inserto 1");
                    } else if (imc <= 24.9) {
                        imagen = new ImageIcon("src/Image/2Verde.png");
                        System.out.println("Inserto 2");
                    } else if (imc <= 29.9) {
                        imagen = new ImageIcon("src/Image/3Amarillo.png");
                        System.out.println("Inserto 3");
                    } else if (imc <= 34.9) {
                        imagen = new ImageIcon("src/Image/4Naranja.png");
                        System.out.println("Inserto 4");
                    } else if (imc <= 39.9) {
                        imagen = new ImageIcon("src/Image/5Anaranjado.png");
                        System.out.println("Inserto 5");
                    } else {
                        imagen = new ImageIcon("src/Image/6Rojo.png");
                        System.out.println("Inserto 6");
                    }

                    // Establecer la imagen en el JLabel
                    LabelIMC.setIcon(imagen);
                } catch (NumberFormatException ex) {
                    // En caso de que el texto no sea un número válido, no se actualiza la imagen
                    LabelIMC.setIcon(null);
                    System.out.println(ex);
                }
            }
        });*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Lcliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lcliente2 = new javax.swing.JLabel();
        arttxt = new javax.swing.JTextField();
        buscartbtn = new javax.swing.JButton();
        provtxt = new javax.swing.JTextField();
        buscarprovbtn = new javax.swing.JButton();
        Lcliente7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        articulosarea = new javax.swing.JTextArea();
        Lcliente3 = new javax.swing.JLabel();
        ctotaltxt = new javax.swing.JTextField();
        confirmarbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        compratxt = new javax.swing.JTextArea();
        Lcliente1 = new javax.swing.JLabel();
        Lcliente4 = new javax.swing.JLabel();
        añadirbtn = new javax.swing.JButton();
        articuloctxt = new javax.swing.JTextField();
        Lcliente5 = new javax.swing.JLabel();
        Lcliente6 = new javax.swing.JLabel();
        provdisp = new javax.swing.JButton();
        confirmarbtn1 = new javax.swing.JButton();
        Lcliente8 = new javax.swing.JLabel();
        Lcliente10 = new javax.swing.JLabel();
        Lcliente11 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 246, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(200, 300));
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(300, 200, 1155, 720));
        setResizable(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(251, 250, 248));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lcliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(Lcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Lcliente2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente2.setText("Ingrese el nombre del producto:");
        jPanel1.add(Lcliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, -1, 20));

        arttxt.setBackground(new java.awt.Color(251, 250, 248));
        arttxt.setCaretColor(new java.awt.Color(153, 153, 153));
        arttxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(arttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 390, -1));

        buscartbtn.setBackground(new java.awt.Color(255, 145, 77));
        buscartbtn.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        buscartbtn.setForeground(new java.awt.Color(251, 250, 248));
        buscartbtn.setText("Buscar producto");
        buscartbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscartbtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscartbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 83, 390, 30));

        provtxt.setBackground(new java.awt.Color(251, 250, 248));
        provtxt.setCaretColor(new java.awt.Color(153, 153, 153));
        provtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(provtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, -1));

        buscarprovbtn.setBackground(new java.awt.Color(255, 145, 77));
        buscarprovbtn.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        buscarprovbtn.setForeground(new java.awt.Color(251, 250, 248));
        buscarprovbtn.setText("Buscar por proveedor");
        buscarprovbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarprovbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarprovbtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscarprovbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, -1));

        Lcliente7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente7.setText("Ingrese el id del Provedor:");
        jPanel1.add(Lcliente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        articulosarea.setEditable(false);
        articulosarea.setColumns(20);
        articulosarea.setRows(5);
        jScrollPane2.setViewportView(articulosarea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 580, 330));

        Lcliente3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente3.setText("TOTAL DE COMPRA");
        jPanel1.add(Lcliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        ctotaltxt.setEditable(false);
        ctotaltxt.setBackground(new java.awt.Color(204, 204, 204));
        ctotaltxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ctotaltxt.setCaretColor(new java.awt.Color(153, 153, 153));
        ctotaltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(ctotaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 210, -1));

        confirmarbtn.setBackground(new java.awt.Color(255, 145, 77));
        confirmarbtn.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        confirmarbtn.setForeground(new java.awt.Color(251, 250, 248));
        confirmarbtn.setText("Confirmar compra");
        confirmarbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarbtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 170, -1));

        compratxt.setEditable(false);
        compratxt.setColumns(20);
        compratxt.setRows(5);
        jScrollPane3.setViewportView(compratxt);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 444, 150));

        Lcliente1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lcliente1.setText("Articulo");
        jPanel1.add(Lcliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        Lcliente4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lcliente4.setText("No. unidades");
        jPanel1.add(Lcliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        añadirbtn.setBackground(new java.awt.Color(255, 145, 77));
        añadirbtn.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        añadirbtn.setForeground(new java.awt.Color(251, 250, 248));
        añadirbtn.setText("Añadir al carrito");
        añadirbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añadirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirbtnActionPerformed(evt);
            }
        });
        jPanel1.add(añadirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 170, -1));

        articuloctxt.setBackground(new java.awt.Color(251, 250, 248));
        articuloctxt.setCaretColor(new java.awt.Color(153, 153, 153));
        articuloctxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        articuloctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloctxtActionPerformed(evt);
            }
        });
        jPanel1.add(articuloctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 260, -1));

        Lcliente5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lcliente5.setText("Precio por unidad");
        jPanel1.add(Lcliente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        Lcliente6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lcliente6.setText("Stock actual");
        jPanel1.add(Lcliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, -1, -1));

        provdisp.setBackground(new java.awt.Color(255, 145, 77));
        provdisp.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        provdisp.setForeground(new java.awt.Color(251, 250, 248));
        provdisp.setText("Lista de proveedores");
        provdisp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        provdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provdispActionPerformed(evt);
            }
        });
        jPanel1.add(provdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, -1));

        confirmarbtn1.setBackground(new java.awt.Color(255, 145, 77));
        confirmarbtn1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        confirmarbtn1.setForeground(new java.awt.Color(251, 250, 248));
        confirmarbtn1.setText("Eliminar articulo");
        confirmarbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 170, -1));

        Lcliente8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lcliente8.setText("No sabes quienes son los  provedores?");
        jPanel1.add(Lcliente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Lcliente10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Lcliente10.setForeground(new java.awt.Color(255, 145, 77));
        Lcliente10.setText("Proceso de compra");
        jPanel1.add(Lcliente10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        Lcliente11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente11.setText("Ingrese el id del producto:");
        jPanel1.add(Lcliente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        Fondo.setBackground(new java.awt.Color(255, 145, 77));
        Fondo.setPreferredSize(new java.awt.Dimension(836, 336));
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoMousePressed(evt);
            }
        });
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(193, 86, 14));
        Salir.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Fondo.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 60, 53));

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Compra de Productos");
        Fondo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, -1));

        Regresarbtn.setBackground(new java.awt.Color(193, 86, 14));
        Regresarbtn.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Regresarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Regresarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresarbtn.setMaximumSize(new java.awt.Dimension(10, 8));
        Regresarbtn.setMinimumSize(new java.awt.Dimension(10, 8));
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });
        Fondo.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 575, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void SetImageButton(String url, JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);

        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
        boton.setOpaque(false);
        this.repaint();
    }
    
    private void añadirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirbtnActionPerformed
        String prod = articuloctxt.getText();
        String canti = JOptionPane.showInputDialog("Ingrese la cantidad a comprar: ");
        int cant = Integer.parseInt(canti);
        exclusivoCompraprov g = new exclusivoCompraprov();
        try{
            g.Borrarcompra();
            g.Compra(canti);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        String datos_e =""; 
        datos_e = g.BuscarProducto(prod, cant);
        compratxt.append(datos_e);
        String t = g.Total(prod, cant);
        ctotaltxt.setText(t);
        articuloctxt.setEditable(false);

    }//GEN-LAST:event_añadirbtnActionPerformed

    private void buscartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscartbtnActionPerformed
        String articulo = arttxt.getText(); 
         exclusivoCompraprov g = new exclusivoCompraprov();
        String datos_e = g.BuscarPArticulo(articulo);
        
        articulosarea.setText(datos_e);
       
    }//GEN-LAST:event_buscartbtnActionPerformed

    private void buscarprovbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarprovbtnActionPerformed
         String proveedor = provtxt.getText();
         String datos_e;
         try{
             int prov = Integer.parseInt(proveedor);
             exclusivoCompraprov g = new exclusivoCompraprov();            
        datos_e = g.BuscarProv(Integer.toString(prov));
         }catch(Exception e){
             datos_e = "Caracteres ingresados erróneos, verifique la clave ingresada";
         }
        
        
        articulosarea.setText(datos_e);
    }//GEN-LAST:event_buscarprovbtnActionPerformed

    private void confirmarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarbtnActionPerformed
        exclusivoCompraprov g = new exclusivoCompraprov();
        String compra = g.cargarCompra();
        String prod = articuloctxt.getText();
        g.Confirmar(compra, prod);
        articuloctxt.setEditable(true);
       String c = g.BuscarProducto(prod, Integer.parseInt(compra));
        compratxt.setText(c);
        
    }//GEN-LAST:event_confirmarbtnActionPerformed

    private void articuloctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articuloctxtActionPerformed

    private void provdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provdispActionPerformed
            String prov;
            exclusivoCompraprov g = new exclusivoCompraprov();
            prov = g.Proveedores();
            articulosarea.setText("              LISTA DE PROVEEDORES" +"\n"+prov);
    }//GEN-LAST:event_provdispActionPerformed

    private void confirmarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarbtn1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Articulo eliminado con éxito");
        exclusivoCompraprov g = new exclusivoCompraprov();
        ctotaltxt.setText("");
       try{
           g.Borrarcompra();
       }catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, e);
       }
       
        compratxt.setText("");
        articuloctxt.setEditable(true);
    }//GEN-LAST:event_confirmarbtn1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        // TODO add your handling code here:

        int R = JOptionPane.showConfirmDialog(null, "Estas Seguro de regresar?", "Regresar", JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE);

        if (R == 0) {
            Perfil_Empleado Perfil = new Perfil_Empleado();
            Perfil.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_RegresarbtnActionPerformed

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged
        // TODO add your handling code here:

        int CX = this.getLocation().x;
        int CY = this.getLocation().y;

        int MoveX = ((CX + evt.getX()) - (CX + mPoint.x));
        int MoveY = ((CY + evt.getY()) - (CY + mPoint.y));

        int x = CX + MoveX;
        int y = CY + MoveY;

        this.setLocation(x, y);
    }//GEN-LAST:event_FondoMouseDragged

    private void FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMousePressed
        // TODO add your handling code here:
        mPoint = evt.getPoint();
        getComponentAt(mPoint);
    }//GEN-LAST:event_FondoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compraprod().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Lcliente;
    private javax.swing.JLabel Lcliente1;
    private javax.swing.JLabel Lcliente10;
    private javax.swing.JLabel Lcliente11;
    private javax.swing.JLabel Lcliente2;
    private javax.swing.JLabel Lcliente3;
    private javax.swing.JLabel Lcliente4;
    private javax.swing.JLabel Lcliente5;
    private javax.swing.JLabel Lcliente6;
    private javax.swing.JLabel Lcliente7;
    private javax.swing.JLabel Lcliente8;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField articuloctxt;
    private javax.swing.JTextArea articulosarea;
    private javax.swing.JTextField arttxt;
    private javax.swing.JButton añadirbtn;
    private javax.swing.JButton buscarprovbtn;
    private javax.swing.JButton buscartbtn;
    private javax.swing.JTextArea compratxt;
    private javax.swing.JButton confirmarbtn;
    private javax.swing.JButton confirmarbtn1;
    private javax.swing.JTextField ctotaltxt;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton provdisp;
    private javax.swing.JTextField provtxt;
    // End of variables declaration//GEN-END:variables
}
