/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import com.google.zxing.*;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.*;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Jesus
 */
public final class Perfil_Segi extends javax.swing.JFrame {

    // Obtener la fecha actual
    LocalDate fechaActual = LocalDate.now();

    // Formatear la fecha como una cadena en el formato deseado (YYYY-MM-DD)
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String fechaFormateada = fechaActual.format(formatter);

    private JPanelConFondo fondo;
    public File archivoSeleccionado;
    private Point mPoint;

    public Perfil_Segi() {
        setUndecorated(true);
        initComponents();

        this.setLocationRelativeTo(this);
        System.out.println(Variables.IDU);

        // Establece la imagen de fondo del JPanel FUNCIONA
        fondo = new JPanelConFondo("src/Image/perfilF.png");
        Fondo.setLayout(new BorderLayout());
        Fondo.add(fondo);

        //colocar id
        ID.setText(Variables.getIDU());
        // System.out.println("Perfil : " + Variables.getIDU());

        idIG.setText(Variables.getIDU());

        imagenBtn_EoR("src/Image/X.png", Salir);
        SetImageButton("src/Image/Ajustes.png", Editarbtn);
           imagenBtn_EoR("src/Image/regresar.png", Regresarbtn);

        Cargarbtn.show(false);
        Guardarbtn.show(false);
        Buscardatos(ID);
        GenerarRutinas(ID);

        if (tblRutinas.getRowCount() > 0) {
            BtnEntrevistaR.show(false);
        } else {
            BtnEntrevistaR.show(true);
        }
        //fecha del dispositivo
        fecha.setText(fechaFormateada);
        TablaSegimineto(ID);
        GraficaSeguimiento();
jButton1.show(false);
    }

    private void imagenBtn_EoR(String url, JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);

        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
        boton.setOpaque(false);
        this.repaint();
    }

    private void SetImageButton(String url, JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth() - 10, boton.getHeight() - 10, Image.SCALE_SMOOTH));
        boton.setIcon(icon);

        boton.setBorderPainted(false);
        // boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
        boton.setOpaque(false);
        this.repaint();
    }

    private void seleccionarImagen() {
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            ImageIcon imagenSeleccionada = new ImageIcon(archivoSeleccionado.getPath());

            //Se escala la imagen al tamaño deseado
            Image imagen = imagenSeleccionada.getImage();
            int ancho = 200;
            int alto = 240;
            Image imagenCamb = imagen.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

            ImageIcon imagen2 = new ImageIcon(imagenCamb);

            FOTOP.setIcon(imagen2);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        FOTOP = new javax.swing.JLabel();
        BtnEntrevistaR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NomUsetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Mtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        QRID = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        pesotxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        imctxt = new javax.swing.JTextField();
        alturatxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRutinas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        ApellidoM = new javax.swing.JTextField();
        celulartxt = new javax.swing.JTextField();
        ApellidoP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        correotxt = new javax.swing.JTextField();
        Perfil = new javax.swing.JLabel();
        Cargarbtn = new javax.swing.JButton();
        Editarbtn = new javax.swing.JButton();
        Guardarbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        correo1 = new javax.swing.JTextField();
        contra2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idIG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pesoSe = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        SegimientoTabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        graficaSeg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 570));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 145, 77));
        Fondo.setMaximumSize(new java.awt.Dimension(863, 329));
        Fondo.setMinimumSize(new java.awt.Dimension(863, 329));
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoMousePressed(evt);
            }
        });

        FOTOP.setBackground(new java.awt.Color(204, 255, 204));
        FOTOP.setForeground(new java.awt.Color(204, 102, 0));
        FOTOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IMAGENES JESUS/add ima.png"))); // NOI18N
        FOTOP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnEntrevistaR.setText("Realizar Entrevista ");
        BtnEntrevistaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrevistaRActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(67, 16, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Usuario");

        NomUsetxt.setEditable(false);
        NomUsetxt.setBackground(new java.awt.Color(240, 239, 239));
        NomUsetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomUsetxtActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(67, 16, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Membresia");

        Mtxt.setEditable(false);
        Mtxt.setBackground(new java.awt.Color(240, 239, 239));
        Mtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(67, 15, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id del Cliente");

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(240, 239, 239));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        QRID.setBackground(new java.awt.Color(204, 255, 204));
        QRID.setForeground(new java.awt.Color(204, 102, 0));
        QRID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IMAGENES JESUS/Commons_QR_code.png"))); // NOI18N
        QRID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Salir.setBackground(new java.awt.Color(193, 86, 14));
        Salir.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(67, 16, 0));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Peso Inicial:");

        pesotxt.setEditable(false);
        pesotxt.setBackground(new java.awt.Color(240, 239, 239));
        pesotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesotxtActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(67, 16, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("IMC Inicial:");

        imctxt.setEditable(false);
        imctxt.setBackground(new java.awt.Color(240, 239, 239));
        imctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imctxtActionPerformed(evt);
            }
        });

        alturatxt.setEditable(false);
        alturatxt.setBackground(new java.awt.Color(240, 239, 239));
        alturatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturatxtActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(67, 16, 0));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Altura:");

        Regresarbtn.setBackground(new java.awt.Color(193, 86, 14));
        Regresarbtn.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Regresarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Regresarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresarbtn.setMaximumSize(new java.awt.Dimension(10, 8));
        Regresarbtn.setMinimumSize(new java.awt.Dimension(10, 8));
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(FOTOP, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomUsetxt)
                            .addComponent(jLabel2)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alturatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(BtnEntrevistaR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(QRID)
                        .addGap(63, 63, 63))
                    .addComponent(Regresarbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FOTOP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomUsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Mtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(pesotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(alturatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEntrevistaR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(Regresarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(QRID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 320));

        jTabbedPane2.setBackground(new java.awt.Color(255, 145, 77));
        jTabbedPane2.setMaximumSize(new java.awt.Dimension(900, 75));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(900, 75));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(900, 75));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(898, 480));

        jPanel2.setBackground(new java.awt.Color(251, 250, 248));
        jPanel2.setMaximumSize(new java.awt.Dimension(863, 90));
        jPanel2.setMinimumSize(new java.awt.Dimension(863, 90));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(895, 477));

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel7.setText("Rutinas");

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 145, 77));
        jLabel6.setText("Recomendadas");

        tblRutinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rutina", "Descripcion", "Duracion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRutinas.setSelectionBackground(new java.awt.Color(255, 145, 77));
        jScrollPane4.setViewportView(tblRutinas);
        if (tblRutinas.getColumnModel().getColumnCount() > 0) {
            tblRutinas.getColumnModel().getColumn(0).setResizable(false);
            tblRutinas.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblRutinas.getColumnModel().getColumn(1).setResizable(false);
            tblRutinas.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblRutinas.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane2.addTab("Rutinas", jScrollPane1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(898, 480));

        jPanel3.setBackground(new java.awt.Color(251, 250, 248));
        jPanel3.setMaximumSize(new java.awt.Dimension(863, 90));
        jPanel3.setMinimumSize(new java.awt.Dimension(863, 90));
        jPanel3.setPreferredSize(new java.awt.Dimension(895, 477));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombres:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Apellido Materno:");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Celular:");

        Nombre.setEditable(false);
        Nombre.setBackground(new java.awt.Color(240, 239, 239));
        Nombre.setToolTipText("");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        ApellidoM.setEditable(false);
        ApellidoM.setBackground(new java.awt.Color(240, 239, 239));
        ApellidoM.setToolTipText("");
        ApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoMActionPerformed(evt);
            }
        });

        celulartxt.setEditable(false);
        celulartxt.setBackground(new java.awt.Color(240, 239, 239));
        celulartxt.setToolTipText("");
        celulartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celulartxtActionPerformed(evt);
            }
        });

        ApellidoP.setEditable(false);
        ApellidoP.setBackground(new java.awt.Color(240, 239, 239));
        ApellidoP.setToolTipText("");
        ApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Apellido Paterno:");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Correo:");

        correotxt.setEditable(false);
        correotxt.setBackground(new java.awt.Color(240, 239, 239));
        correotxt.setToolTipText("");
        correotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correotxtActionPerformed(evt);
            }
        });

        Perfil.setBackground(new java.awt.Color(204, 255, 204));
        Perfil.setForeground(new java.awt.Color(204, 102, 0));
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfildef.png"))); // NOI18N

        Cargarbtn.setText("Cambiar Imagen");
        Cargarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarbtnActionPerformed(evt);
            }
        });

        Editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbtnActionPerformed(evt);
            }
        });

        Guardarbtn.setText("Guardar");
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Contrasena nueva:");

        correo1.setEditable(false);
        correo1.setBackground(new java.awt.Color(240, 239, 239));
        correo1.setToolTipText("");
        correo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo1ActionPerformed(evt);
            }
        });

        contra2.setEditable(false);
        contra2.setBackground(new java.awt.Color(240, 239, 239));
        contra2.setToolTipText("");
        contra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contra2ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Repetir contrasena:");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Id:");

        idIG.setEditable(false);
        idIG.setBackground(new java.awt.Color(240, 239, 239));
        idIG.setToolTipText("");
        idIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idIGActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        jLabel9.setText("Datos");

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 145, 77));
        jLabel12.setText("del cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idIG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(ApellidoP, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celulartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(contra2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(ApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Editarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Cargarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Perfil)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)))
                            .addComponent(Editarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(1, 1, 1)
                                .addComponent(idIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(1, 1, 1)
                                .addComponent(ApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(1, 1, 1)
                                .addComponent(ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(1, 1, 1)
                                .addComponent(celulartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cargarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane2.addTab("Informacion General", jScrollPane2);

        jPanel7.setBackground(new java.awt.Color(251, 250, 248));
        jPanel7.setMaximumSize(new java.awt.Dimension(863, 90));
        jPanel7.setMinimumSize(new java.awt.Dimension(863, 90));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel17.setText("Seguimiento");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 22, -1, -1));

        jLabel18.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 145, 77));
        jLabel18.setText("Cliente");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 22, -1, -1));

        jLabel19.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 145, 77));
        jLabel19.setText("del");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 22, -1, -1));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(240, 239, 239));
        fecha.setToolTipText("");
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jPanel7.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 106, 163, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Fecha: ");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 108, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Peso Actual:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 108, -1, -1));

        pesoSe.setBackground(new java.awt.Color(255, 255, 255));
        pesoSe.setToolTipText("");
        pesoSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoSeActionPerformed(evt);
            }
        });
        jPanel7.add(pesoSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 106, 165, -1));

        SegimientoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Semana", "Fecha", "Peso Actual", "IMC Actual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SegimientoTabla.setSelectionBackground(new java.awt.Color(255, 145, 77));
        jScrollPane5.setViewportView(SegimientoTabla);
        if (SegimientoTabla.getColumnModel().getColumnCount() > 0) {
            SegimientoTabla.getColumnModel().getColumn(0).setResizable(false);
            SegimientoTabla.getColumnModel().getColumn(1).setResizable(false);
            SegimientoTabla.getColumnModel().getColumn(2).setResizable(false);
            SegimientoTabla.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 423, 155));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 106, 111, -1));

        graficaSeg.setMaximumSize(new java.awt.Dimension(800, 600));
        graficaSeg.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout graficaSegLayout = new javax.swing.GroupLayout(graficaSeg);
        graficaSeg.setLayout(graficaSegLayout);
        graficaSegLayout.setHorizontalGroup(
            graficaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        graficaSegLayout.setVerticalGroup(
            graficaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel7.add(graficaSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 440, 290));

        jScrollPane3.setViewportView(jPanel7);

        jTabbedPane2.addTab("Segimiento del cliente", jScrollPane3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 970, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void MtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtActionPerformed

    private void NomUsetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomUsetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomUsetxtActionPerformed

    private void BtnEntrevistaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrevistaRActionPerformed
        // TODO add your handling code here:
        entrevista_rutina rEntrevista = new entrevista_rutina();
        rEntrevista.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BtnEntrevistaRActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int R = JOptionPane.showConfirmDialog(null, "Estas seguro de salir?", "Salir", JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE);

        if (R == 0) {
        System.exit(0);}
    }//GEN-LAST:event_SalirActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoMActionPerformed

    private void celulartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celulartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celulartxtActionPerformed

    private void ApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPActionPerformed

    private void correotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correotxtActionPerformed

    private void CargarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarbtnActionPerformed

        //METODO PARA CARGAR IMAGEN desde el explorador
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            String ruta = archivoSeleccionado.getName();
            System.out.println(ruta);

            try {
                Image imagenSeleccionada = ImageIO.read(archivoSeleccionado);
                ImageIcon Imagen = new ImageIcon(imagenSeleccionada);

                int labelancho = Perfil.getWidth();
                int labellargo = Perfil.getHeight();

                Image scaledImage = Imagen.getImage().getScaledInstance(labelancho, labellargo, Image.SCALE_SMOOTH);

                Perfil.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            }
        }

    }//GEN-LAST:event_CargarbtnActionPerformed

    private void correo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo1ActionPerformed

    private void contra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contra2ActionPerformed

    private void idIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idIGActionPerformed

    private void EditarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbtnActionPerformed
        // TODO add your handling code here:
        Cargarbtn.show(true);
        Guardarbtn.show(true);
        correotxt.setEditable(true);
        celulartxt.setEditable(true);
        contra2.setEditable(true);
        correo1.setEditable(true);
        correotxt.setBackground(Color.WHITE);
        celulartxt.setBackground(Color.WHITE);
        contra2.setBackground(Color.WHITE);
        correo1.setBackground(Color.WHITE);


    }//GEN-LAST:event_EditarbtnActionPerformed

    private void FondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoMouseClicked

    private void FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMousePressed
        // TODO add your handling code here:
        mPoint = evt.getPoint();
        getComponentAt(mPoint);
    }//GEN-LAST:event_FondoMousePressed

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged
        // TODO add your handling code here:
        int CX = this.getLocation().x;
        int CY = this.getLocation().y;

        int MoveX = ((CX + evt.getX()) - (CX + mPoint.x));
        int MoveY = ((CY + evt.getY()) - (CY + mPoint.y));

        int x = CX + MoveX;
        int y = CY + MoveY;

        this.setLocation(x, y);
    }//GEN-LAST:event_FondoMouseDragged

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed

        // TODO add your handling code here:
        ActualizarDatos(ID, celulartxt, correotxt, correo1, contra2, archivoSeleccionado);

    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        saveQRToDatabase(ID, generateQRCode(ID.getText(), QRID));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesoSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoSeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoSeActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void pesotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesotxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SeguimientoCLiente(ID, pesoSe, alturatxt);
        TablaSegimineto(ID);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void imctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imctxtActionPerformed

    private void alturatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturatxtActionPerformed

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        // TODO add your handling code here:

        int R = JOptionPane.showConfirmDialog(null, "Estas Seguro de cerrar Sesion", "Si", JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE);

        if (R == 0) {
            login Perfil = new login();
            Perfil.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_RegresarbtnActionPerformed

    public void GenerarRutinas(JTextField ID) {
        try {

            conectar ObjetoConexion = new conectar();
            String generar = "SELECT d.id_Cliente, d.id_Rutina, r.ejercicios, r.descripcion, r.duracion_total "
                    + "FROM detalles_rutina d "
                    + "JOIN rutina r ON d.id_Rutina = r.id_Rutina "
                    + "WHERE d.id_Cliente = ?;";

            // Preparar la declaración SQL
            PreparedStatement ps = ObjetoConexion.prepareStatement(generar);

            // Establecer el valor del parámetro en la consulta SQL
            ps.setString(1, ID.getText());

            ResultSet resultado = ps.executeQuery();
            // Ejecutar la consulta y obtener el ResultSet
            resultado = ps.executeQuery();

            // Crear un DefaultTableModel para almacenar los datos
            DefaultTableModel modeloTabla = (DefaultTableModel) tblRutinas.getModel();
            // Eliminar las filas existentes de la tabla
            modeloTabla.setRowCount(0);

            // Agregar las filas al modelo de tabla
            while (resultado.next()) {
                Object[] fila = {
                    //resultado.getString("id_Cliente"),
                    // resultado.getString("id_Rutina"),
                    resultado.getString("ejercicios"),
                    resultado.getString("descripcion"),
                    resultado.getString("duracion_total")
                };
                modeloTabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    public void Buscardatos(JTextField ID) {
        try {
            conectar ObjetoConexion = new conectar();

            String cosulta = "SELECT * FROM cliente WHERE id_cliente=?";

            PreparedStatement ps = ObjetoConexion.prepareStatement(cosulta);

            ps.setString(1, ID.getText());

            ResultSet resultado = ps.executeQuery();

            if (resultado.next()) {
                String nombre = resultado.getString("nombreC");
                String apellidoP = resultado.getString("apellidoPC");
                String apellidoM = resultado.getString("apellidoMC");
                String correo = resultado.getString("correoC");
                int celular = resultado.getInt("celularC");
                String membresia = resultado.getString("membresia");
                byte[] fotoBytes = resultado.getBytes("foto");
                String contra = resultado.getString("contrasena");
                Double peso_inicial = resultado.getDouble("peso_inicial");
                Double altura = resultado.getDouble("estatura");
                Double imc = resultado.getDouble("imc");

                // Convertir arreglo de bytes a ImageIcon
                ImageIcon imagen = new ImageIcon(fotoBytes);
                // Escalar la imagen si es necesario
                Image imagenEscalada = imagen.getImage().getScaledInstance(FOTOP.getWidth(), FOTOP.getHeight(), Image.SCALE_SMOOTH);
                Image imagenEscalada2 = imagen.getImage().getScaledInstance(Perfil.getWidth(), Perfil.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imagenEscaladaIcon = new ImageIcon(imagenEscalada);
                ImageIcon imagenEscaladaIcon2 = new ImageIcon(imagenEscalada2);

                // Asignar la imagen al JLabel
                FOTOP.setIcon(imagenEscaladaIcon);
                Perfil.setIcon(imagenEscaladaIcon2);

                NomUsetxt.setText(nombre + " " + apellidoP + " " + apellidoM);
                Mtxt.setText(membresia);
                pesotxt.setText(String.valueOf(peso_inicial));
                Nombre.setText(nombre);
                ApellidoP.setText(apellidoP);
                ApellidoM.setText(apellidoM);
                correotxt.setText(correo);
                celulartxt.setText(String.valueOf(celular));
                correo1.setText(contra);
                contra2.setText(contra);
                alturatxt.setText(String.valueOf(altura));
                imctxt.setText(String.valueOf(imc));

            } else {
               // JOptionPane.showMessageDialog(null, "No se pudo encontrar al usuario");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }

    }

    public void ActualizarDatos(JTextField ID, JTextField celular, JTextField correo, JTextField contrasena, JTextField contrasenaRep, File foto) {
        if (contrasena.getText().equals(contrasenaRep.getText())) {
            try {
                //conectar BD
                conectar ObjetoConexion = new conectar();

                 //Generar consulta
                String actualizar = "update cliente set celularC =?,correoC = ?,contrasena = ?, foto= ?  where id_cliente= ?;";
                FileInputStream fis = new FileInputStream(foto);
                PreparedStatement ps = ObjetoConexion.prepareStatement(actualizar);

                    //poner los datos
                ps.setInt(1, Integer.parseInt(celular.getText())); 
                ps.setString(2, correo.getText());
                ps.setString(3, contrasena.getText());
                ps.setBinaryStream(4, fis, (int) foto.length());
                ps.setString(5, ID.getText());
                // Ejecutar la sentencia SQL de actualización
                int filasActualizadas = ps.executeUpdate();
                // Verificar si se actualizaron filas y mostrar un mensaje
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(null, "Se guardo correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Lo sentimos, NO guardo correctamente");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error A: " + e.toString());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Perfil_Segi.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La contrasena no son similares");
            contrasena.setText("");
            contrasenaRep.setText("");
        }

    }

    public void SeguimientoCLiente(JTextField ID, JTextField pesoactual, JTextField altura) {

        try {

            conectar ObjetoConexion = new conectar();

            //  String actualizacion="UPDATE cliente set peso_inicial =?";
            String insert = "INSERT INTO seguimientoCl (id_Cliente, fecha, semana, pesoActual,imcActual) "
                    + "SELECT ?, ?, COALESCE(MAX(semana), 0) + 1, ?,?"
                    + "FROM seguimientoCl WHERE id_Cliente = ?;";

            Double altura1 = Double.parseDouble(altura.getText());
            // peso / (altura * altura);
            Double imc = Double.parseDouble(pesoactual.getText()) / (altura1 * altura1);
            DecimalFormat formato = new DecimalFormat("#.##");
            String numeroFormateado = formato.format(imc);

            PreparedStatement psI = ObjetoConexion.prepareStatement(insert);

            psI.setString(1, ID.getText());
            psI.setDate(2, java.sql.Date.valueOf(fechaActual));
            psI.setDouble(3, Double.parseDouble(pesoactual.getText()));
            psI.setDouble(4, Double.parseDouble(numeroFormateado));
            psI.setString(5, ID.getText());

            psI.executeUpdate();
            JOptionPane.showMessageDialog(null, "Guardado con EXITO");

        } catch (NumberFormatException | SQLException e) {

            JOptionPane.showMessageDialog(null, e.toString());

        }

    }

    public void TablaSegimineto(JTextField ID) {
        try {
            conectar ObjetoConexion = new conectar();
            //
            String consulta = "SELECT * FROM seguimientoCl WHERE id_Cliente=?";
            PreparedStatement psC = ObjetoConexion.prepareStatement(consulta);

            psC.setString(1, ID.getText());

            ResultSet resultado = psC.executeQuery();
            // Crear un DefaultTableModel para almacenar los datos
            DefaultTableModel modeloTabla = (DefaultTableModel) SegimientoTabla.getModel();
            // Eliminar las filas existentes de la tabla -------------------------------checar eso
            modeloTabla.setRowCount(0);

            // Agregar las filas al modelo de tabla
            while (resultado.next()) {
                Object[] fila2 = {
                    //resultado.getString("id_Cliente"),
                    // resultado.getString("id_Rutina"),
                    resultado.getString("semana"),
                    resultado.getString("fecha"),
                    resultado.getDouble("pesoActual"),
                    resultado.getDouble("imcActual")
                };
                modeloTabla.addRow(fila2);
            }
            GraficaSeguimiento();
        } catch (Exception e) {
        }
    }

    public void GraficaSeguimiento() {
        try {
            //GENERAR LA GRAFICA
            XYSeries seguimiento = new XYSeries("Seguimiento del Cliente");
            for (int i = 0; i < SegimientoTabla.getRowCount(); i++) {
                // Obtener los datos de la tabla como objetos
                Object semanaObject = SegimientoTabla.getValueAt(i, 0);
                Object pesoObject = SegimientoTabla.getValueAt(i, 2);

                // Convertir la semana de String a Double
                double semana;
                if (semanaObject instanceof String string) {
                    try {
                        semana = Double.parseDouble(string);
                    } catch (NumberFormatException ex) {
                        System.out.println("Error al convertir la semana en la fila " + i + ": " + ex.getMessage());
                        continue; // Saltar esta fila y pasar a la siguiente iteración del bucle
                    }
                } else if (semanaObject instanceof Double aDouble) {
                    semana = aDouble;
                } else {
                    System.out.println("Error: Tipo de datos no válido para la semana en la fila " + i);
                    continue; // Saltar esta fila y pasar a la siguiente iteración del bucle
                }

                // Verificar si el peso es un Double
                if (!(pesoObject instanceof Double)) {
                    System.out.println("Error: Tipo de datos no válido para el peso en la fila " + i);
                    continue; // Saltar esta fila y pasar a la siguiente iteración del bucle
                }

                // Convertir el peso de Double a double
                double peso = (Double) pesoObject;

                // Agregar los datos a la serie
                seguimiento.add(semana, peso);
            }

            //CREACION DE GRAFICA LINEAS
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(seguimiento);

            JFreeChart chart = ChartFactory.createXYLineChart("", "Semanas", "Peso", dataset, PlotOrientation.VERTICAL, true, true, false);
            
         XYPlot plot = chart.getXYPlot();
        NumberAxis domainAxis = (NumberAxis) plot.getDomainAxis();
        domainAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

            // Crear el ChartPanel y añadirlo al JPanel existente
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(800, 600));

            this.graficaSeg.removeAll();  // Limpiar cualquier componente existente
            this.graficaSeg.setLayout(new BorderLayout());  // Establecer el layout
            this.graficaSeg.add(chartPanel, BorderLayout.CENTER);
            this.graficaSeg.validate();  // Validar el JPanel para actualizarlo

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    //Generar QR
    public static byte[] generateQRCode(String content, JLabel label) {
        int size = 1000; // Tamaño del código QR

        try {

            // Configuración para la generación del código QR
            Hashtable<EncodeHintType, Object> hintMap = new Hashtable<>();
            hintMap.put(EncodeHintType.CHARACTER_SET, "UTF-8");

            // Crear el objeto QRCodeWriter
            QRCodeWriter qrCodeWriter = new QRCodeWriter();

            // Generar la matriz de bits del código QR
            BitMatrix bitMatrix = qrCodeWriter.encode(content, BarcodeFormat.QR_CODE, size, size, hintMap);

            // Crear la imagen del código QR
            int matrixWidth = bitMatrix.getWidth();
            BufferedImage image = new BufferedImage(matrixWidth, matrixWidth, BufferedImage.TYPE_INT_RGB);
            image.createGraphics();

            // Renderizar la matriz de bits en la imagen del código QR
            Graphics2D graphics2D = (Graphics2D) image.getGraphics();
            graphics2D.setColor(Color.WHITE);
            graphics2D.fillRect(0, 0, matrixWidth, matrixWidth);
            graphics2D.setColor(Color.BLACK);

            for (int x = 0; x < matrixWidth; x++) {
                for (int y = 0; y < matrixWidth; y++) {
                    if (bitMatrix.get(x, y)) {
                        graphics2D.fillRect(x, y, 1, 1);
                    }
                }
            }

            // Convertir la imagen del código QR a un arreglo de bytes
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(image, "png", baos);
            byte[] qrBytes = baos.toByteArray();

            // Mostrar el código QR en el JLabel
            displayQRCode(qrBytes, label);

            return qrBytes;
        } catch (WriterException | IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static void displayQRCode(byte[] qrBytes, JLabel label) {
        try {
            ByteArrayInputStream bais = new ByteArrayInputStream(qrBytes);
            BufferedImage image = ImageIO.read(bais);
            ImageIcon icon = new ImageIcon(image);
            label.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Guarda el código QR en la base de datos junto con el contenido asociado
    public static void saveQRToDatabase(JTextField ID, byte[] qrBytes) {

        try {
            conectar ObjetoConexion = new conectar();

            String sql = "INSERT INTO cliente (qr) VALUES (?) WHERE id_cliente = ?;";
            try (PreparedStatement statement = ObjetoConexion.prepareStatement(sql)) {
                statement.setString(2, ID.getText());
                statement.setBytes(1, qrBytes);
                statement.executeUpdate();
                System.out.println("Código QR guardado en la base de datos.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Segi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Segi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Segi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Segi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Segi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoM;
    private javax.swing.JTextField ApellidoP;
    private javax.swing.JButton BtnEntrevistaR;
    private javax.swing.JButton Cargarbtn;
    private javax.swing.JButton Editarbtn;
    private javax.swing.JLabel FOTOP;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Mtxt;
    private javax.swing.JTextField NomUsetxt;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Perfil;
    private javax.swing.JLabel QRID;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JButton Salir;
    private javax.swing.JTable SegimientoTabla;
    private javax.swing.JTextField alturatxt;
    private javax.swing.JTextField celulartxt;
    private javax.swing.JTextField contra2;
    private javax.swing.JTextField correo1;
    private javax.swing.JTextField correotxt;
    private javax.swing.JTextField fecha;
    private javax.swing.JPanel graficaSeg;
    private javax.swing.JTextField idIG;
    private javax.swing.JTextField imctxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField pesoSe;
    private javax.swing.JTextField pesotxt;
    private javax.swing.JTable tblRutinas;
    // End of variables declaration//GEN-END:variables

}
