/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import com.mysql.cj.jdbc.CallableStatement;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.FileInputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.imageio.ImageIO;

/**
 *
 * @author Jesus
 */
public class Registro_Cliente extends javax.swing.JFrame {

    //Metodos
    Reglas reglas = new Reglas();
    // Obtener la fecha actual
    LocalDate fechaActual = LocalDate.now();

    // Formatear la fecha como una cadena en el formato deseado (YYYY-MM-DD)
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String fechaFormateada = fechaActual.format(formatter);

    // Establecer la fecha formateada en el JTextField
    //VARIABLES 
    private JPanelConFondo fondo, fondo2;
    public File archivoSeleccionado;
    private Point mPoint;

    public Registro_Cliente() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this);

        // Establece la imagen de fondo del JPanel FUNCIONA
        fondo = new JPanelConFondo("src/Image/perfilF.png");
        Fondo.setLayout(new BorderLayout());
        Fondo.add(fondo);
        
         
        

        SetImageButton("src/Image/X.png", Salir);

        //fecha del dispositivo
        fecha.setText(fechaFormateada);

        
        id.setText(reglas.CrearID("C", fechaFormateada));

    }
    
    private void SetImageButton(String url, JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);

        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
        boton.setOpaque(false);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Cargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Perfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        SiE = new javax.swing.JRadioButton();
        NoE = new javax.swing.JRadioButton();
        ApellidoM = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        membresia = new javax.swing.JComboBox<>();
        ApellidoP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 145, 77));
        Fondo.setPreferredSize(new java.awt.Dimension(836, 336));
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoMousePressed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(193, 86, 14));
        Salir.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Registro de Usuario");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(48, 48, 48))
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(251, 250, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cargar.setText("Cambiar Imagen");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jPanel3.add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 222, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        Perfil.setBackground(new java.awt.Color(204, 255, 204));
        Perfil.setForeground(new java.awt.Color(204, 102, 0));
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfildef.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Materno:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo de membresia:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Sexo:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Estudiante?");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 90, -1));

        Nombre.setBackground(new java.awt.Color(251, 250, 248));
        Nombre.setToolTipText("");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, -1));

        buttonGroup1.add(SiE);
        SiE.setText("SI");
        SiE.setToolTipText("");
        SiE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiEActionPerformed(evt);
            }
        });
        jPanel3.add(SiE, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        buttonGroup1.add(NoE);
        NoE.setText("No");
        NoE.setToolTipText("");
        NoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEActionPerformed(evt);
            }
        });
        jPanel3.add(NoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        ApellidoM.setBackground(new java.awt.Color(251, 250, 248));
        ApellidoM.setToolTipText("");
        ApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoMActionPerformed(evt);
            }
        });
        jPanel3.add(ApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 180, -1));

        celular.setBackground(new java.awt.Color(251, 250, 248));
        celular.setToolTipText("");
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });
        jPanel3.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 200, -1));

        edad.setToolTipText("");
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        jPanel3.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 40, -1));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        sexo.setToolTipText("");
        jPanel3.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        Guardar.setText("Generar Perfil");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel3.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 370, 60));

        membresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Premium" }));
        membresia.setToolTipText("");
        jPanel3.add(membresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 200, 30));

        ApellidoP.setBackground(new java.awt.Color(251, 250, 248));
        ApellidoP.setToolTipText("");
        ApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPActionPerformed(evt);
            }
        });
        jPanel3.add(ApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 180, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Paterno:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Correo:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        correo.setBackground(new java.awt.Color(251, 250, 248));
        correo.setToolTipText("");
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        jPanel3.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 200, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Fecha:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(240, 239, 239));
        id.setToolTipText("");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 140, -1));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(240, 239, 239));
        fecha.setToolTipText("");
        fecha.setCaretColor(new java.awt.Color(153, 153, 153));
        fecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 150, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Id:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed

        //METODO PARA CARGAR IMAGEN desde el explorador
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            String ruta = archivoSeleccionado.getName();
            System.out.println(ruta);

            try {
                Image imagenSeleccionada = ImageIO.read(archivoSeleccionado);
                ImageIcon Imagen = new ImageIcon(imagenSeleccionada);

                int labelancho = Perfil.getWidth();
                int labellargo = Perfil.getHeight();

                Image scaledImage = Imagen.getImage().getScaledInstance(labelancho, labellargo, Image.SCALE_SMOOTH);

                Perfil.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            }
        }


    }//GEN-LAST:event_CargarActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoMActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        //SE Genra Perfil
     //   BD_Movimientos AddCl = new BD_Movimientos();
        try {
             if (SiE.isSelected()) {
            //metodo para agregarlo a la BD de CLiente
            AgregarCliente(Nombre, ApellidoP, ApellidoM, id, membresia, correo, celular,
                    0, 0, 0, "NA", archivoSeleccionado, java.sql.Date.valueOf(fechaActual), sexo, "Si", edad);
        } else if (NoE.isSelected()) {
            AgregarCliente(Nombre, ApellidoP, ApellidoM, id, membresia, correo, celular,
                    0, 0, 0, "NA", archivoSeleccionado, java.sql.Date.valueOf(fechaActual), sexo, "No", edad);
        }

        
        //RReinicio
        id.setText(reglas.CrearID("C", fechaFormateada));
        Nombre.setText("");
        ApellidoP.setText("");
        ApellidoM.setText("");
        celular.setText("");
        correo.setText("");
        edad.setText("");
        SiE.setSelected(false);
        NoE.setSelected(false);
        Perfil.setIcon(null);
        
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.toString());
            //System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_GuardarActionPerformed

    private void NoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoEActionPerformed

    private void ApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void SiEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiEActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged
        // TODO add your handling code here:
        
        int  CX = this.getLocation().x;
        int  CY = this.getLocation().y;
        
        
        int MoveX =((CX+evt.getX()) - (CX+mPoint.x));
        int MoveY =((CY+evt.getY()) - (CY+mPoint.y));

        
        int x = CX+MoveX;
        int y = CY+MoveY;
        
        
        this.setLocation(x, y);
    }//GEN-LAST:event_FondoMouseDragged

    private void FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMousePressed
        // TODO add your handling code here:
        mPoint=evt.getPoint(); 
        getComponentAt(mPoint);
    }//GEN-LAST:event_FondoMousePressed

    
    
      public void AgregarCliente(JTextField nombre, JTextField apellidoP, JTextField apellidoM, JTextField idCliente,
            JComboBox Membresia, JTextField correo, JTextField celular, double peso, double estatura, double imc,
            String motivo, File foto, Date fecha, JComboBox sexo, String estudiante, JTextField edad) {

        conectar ObjetoConexion = new conectar();

        String Alta = "insert into cliente (id_cliente, membresia, nombreC, apellidoPC, "
                + "apellidoMC, correoC, celularC, peso_inicial, estatura, imc, motivo_entre, foto,fecha, sexo, "
                + "estudiante, edad, contrasena)" + "values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?); ";

        try {
            FileInputStream fis = new FileInputStream(foto);

            CallableStatement cs = (CallableStatement) ObjetoConexion.getConexion().prepareCall(Alta);

           

            cs.setString(1, idCliente.getText());
            cs.setString(2, Membresia.getSelectedItem().toString());
            cs.setString(3, nombre.getText());
            cs.setString(4, apellidoP.getText());
            cs.setString(5, apellidoM.getText());
            cs.setString(6, correo.getText());
            cs.setInt(7, Integer.parseInt(celular.getText()));
            cs.setDouble(8, peso);
            cs.setDouble(9, estatura);
            cs.setDouble(10, imc);
            cs.setString(11, motivo);
            cs.setBinaryStream(12, fis, (int) foto.length());
            cs.setDate(13, (java.sql.Date) fecha);
            cs.setString(14, sexo.getSelectedItem().toString());
            cs.setString(15, estudiante);
            cs.setInt(16, Integer.parseInt(edad.getText()));
            cs.setString(17, "PowerGYM123");

            cs.execute();

            JOptionPane.showMessageDialog(null, "Registro COMPLETADO !!!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoM;
    private javax.swing.JTextField ApellidoP;
    private javax.swing.JButton Cargar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JRadioButton NoE;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Perfil;
    private javax.swing.JButton Salir;
    private javax.swing.JRadioButton SiE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> membresia;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables
}
